# Generated by Django 5.1.4 on 2024-12-19 11:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du bien')),
                ('description', models.TextField(verbose_name='Description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur estimée')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('transfer_pending', 'Transfert en cours'), ('archived', 'Archivé')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Biens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/%Y/%m/%d/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
            options={
                'verbose_name': 'Image du bien',
                'verbose_name_plural': 'Images des biens',
            },
        ),
        migrations.CreateModel(
            name='PropertyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('transfer_notes', models.TextField(blank=True)),
                ('transfer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='property.property')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfert de propriété',
                'verbose_name_plural': 'Transferts de propriétés',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
